In [8]:
import numpy as np
a = np.zeros(3)
b = np.argmax(a)
print(b)

0


In [19]:
print(x)
print(W)
print(out.shape)

[[0 3 1 2]
 [2 1 0 3]]
[[ 0.          0.07142857  0.14285714]
 [ 0.21428571  0.28571429  0.35714286]
 [ 0.42857143  0.5         0.57142857]
 [ 0.64285714  0.71428571  0.78571429]
 [ 0.85714286  0.92857143  1.        ]]
(2, 4, 3)
